### ISSUE TITLE
Misleading message when unable to connect due to DNS lookup failure. Part 2.

### ISSUE THREAD

**Issue by NealArw** [UffizziCloud/uffizzi_cli#118]
When the CLI cannot connect to a Uffizzi API server, users may receive a misleading error message:

$ docker run --interactive --rm --tty --entrypoint=bash uffizzi/cli
root@881228c80c70:~# uffizzi login
Login to Uffizzi to view and manage your previews.
Server:  https://devopseu.uffizzicloud.com
Username:  adam.vollrath@uffizzi.com
Password:  
The command was interrupted
This message should probably tell users that the CLI could not connect. In this case it's a DNS lookup failure. (devopseu.uffizzicloud.com is a CNAME that points to another record that no longer exists.)

Needs to implement this task also for next case:

1) URL: `https://test.com` - Valid URL, that can be reached

```
/usr/local/lib/ruby/3.0.0/net/http.rb:987:in `initialize': execution expired (Net::OpenTimeout)
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `open'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:985:in `connect'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:959:in `start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:621:in `start'
	from /usr/local/bundle/gems/uffizzi-cli-0.11.0/lib/uffizzi/clients/api/http_client.rb:38:in `make_request'
	from /usr/local/bundle/gems/uffizzi-cli-0.11.0/lib/uffizzi/clients/api/http_client.rb:21:in `make_post_request'
	from /usr/local/bundle/gems/uffizzi-cli-0.11.0/lib/uffizzi/clients/api/api_client.rb:11:in `create_session'
	from /usr/local/bundle/gems/uffizzi-cli-0.11.0/lib/uffizzi/cli/login.rb:24:in `run'
	from /usr/local/bundle/gems/uffizzi-cli-0.11.0/lib/uffizzi/cli.rb:24:in `login'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/uffizzi-cli-0.11.0/lib/uffizzi/cli.rb:64:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/uffizzi-cli-0.11.0/exe/uffizzi:5:in `<top (required)>'
	from /usr/local/bundle/bin/uffizzi:25:in `load'
	from /usr/local/bundle/bin/uffizzi:25:in `<main>'
```

**Comment by NealArw** [comment]
**Was not fixed:**

```
bash-5.1# bundle exec uffizzi config
Configure the default properties that will be used to authenticate with your
Uffizzi API service and manage previews.
Server:  (app.uffizzi.com) https://test.com
Username:  user@example.com
Project:  (default)
To login, run: uffizzi login
bash-5.1# bundle exec uffizzi login
Login to Uffizzi server.
bundler: failed to load command: uffizzi (/bundle_cache/ruby/3.0.0/bin/uffizzi)
/usr/local/lib/ruby/3.0.0/net/http.rb:987:in `initialize': execution expired (Net::OpenTimeout)
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `open'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:985:in `connect'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:959:in `start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:621:in `start'
	from /gem/lib/uffizzi/clients/api/http_client.rb:38:in `make_request'
	from /gem/lib/uffizzi/clients/api/http_client.rb:21:in `make_post_request'
	from /gem/lib/uffizzi/clients/api/api_client.rb:11:in `create_session'
	from /gem/lib/uffizzi/cli/login.rb:24:in `run'
	from /gem/lib/uffizzi/cli.rb:24:in `login'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /gem/lib/uffizzi/cli.rb:64:in `dispatch'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /gem/exe/uffizzi:5:in `<top (required)>'
	from /bundle_cache/ruby/3.0.0/bin/uffizzi:25:in `load'
	from /bundle_cache/ruby/3.0.0/bin/uffizzi:25:in `<top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:478:in `exec'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:23:in `load'
	from /usr/local/bundle/bin/bundle:23:in `<main>'
bash-5.1#
```

**Comment by NealArw** [comment]
Was not fixed, still reproduced at QA branch.

**Comment by NealArw** [comment]
Also needs to process url in the format `app.uffizzi.com` (without `https://`).
When a user enters the address in same format, add `https://` automatically.

For now, it returns an error:

```
bash-5.1# bundle exec uffizzi config
Configure the default properties that will be used to authenticate with your
Uffizzi API service and manage previews.
Server:  (app.uffizzi.com)
Username:  test@test.com
Project:  (default)
To login, run: uffizzi login
bash-5.1# bundle exec uffizzi login
Login to Uffizzi server.
Failed to open TCP connection to :80 (Address not available - connect(2) for nil port 80)
```

**Comment by moklidia** [comment]
@antlu We should add the `https://` prefix if it's missing

**Comment by NealArw** [comment]
**TESTED - OK**

```
bash-5.1# bundle exec uffizzi config
Configure the default properties that will be used to authenticate with your
Uffizzi API service and manage previews.
Server:  (app.uffizzi.com) test.com
Username:  test
Project:  (default) test
To login, run: uffizzi login

bash-5.1# bundle exec uffizzi login
Login to Uffizzi server.
execution expired

bash-5.1# bundle exec uffizzi config
Configure the default properties that will be used to authenticate with your
Uffizzi API service and manage previews.
Server:  (app.uffizzi.com) http://web:7000
Username:  user@example.com
Project:  (default)
To login, run: uffizzi login

bash-5.1# bundle exec uffizzi login
Login to Uffizzi server.
Login successfull
bash-5.1#
```

**Comment by NealArw** [comment]
**TESTED on prod - OK**
```
# uffizzi config
Configure the default properties that will be used to authenticate with your
Uffizzi API service and manage previews.
Server:  (app.uffizzi.com) test.com
Username:  test
Project:  (default)
To login, run: uffizzi login
# uffizzi login
Login to Uffizzi server.
Password:
execution expired
# 
```

```
# uffizzi config
Configure the default properties that will be used to authenticate with your
Uffizzi API service and manage previews.
Server:  (app.uffizzi.com)
Username:
Project:  (default)
To login, run: uffizzi login
# uffizzi login
Login to Uffizzi server.
Username:  test
Password:
Email or password is incorrect.
#
```

```
# uffizzi config
Configure the default properties that will be used to authenticate with your
Uffizzi API service and manage previews.
Server:  (app.uffizzi.com) https://test.com
Username:  test
Project:  (default)
To login, run: uffizzi login
# uffizzi login
Login to Uffizzi server.
Password:
execution expired
#
```
