### ISSUE TITLE
BUG: CLI uffizzi connect ghcr returns an error

### ISSUE THREAD

**Issue by NealArw** [UffizziCloud/uffizzi_cli#66]
1. `uffizzi connect ghcr` returns an error

<details><summary>Click to expand</summary>

```
bash-5.1# bundle exec uffizzi connect ghcr
Github Username:  NealArw
Access Token:
bundler: failed to load command: uffizzi (/bundle_cache/ruby/3.0.0/bin/uffizzi)
/usr/local/lib/ruby/3.0.0/net/http.rb:987:in `initialize': Failed to open TCP connection to :80 (Address not available - connect(2) for nil port 80) (Errno::EADDRNOTAVAIL)
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `open'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:985:in `connect'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:959:in `start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:621:in `start'
	from /gem/lib/uffizzi/clients/api/http_client.rb:39:in `make_request'
	from /gem/lib/uffizzi/clients/api/http_client.rb:22:in `make_post_request'
	from /gem/lib/uffizzi/clients/api/api_client.rb:32:in `create_credential'
	from /gem/lib/uffizzi/cli/connect.rb:139:in `ghcr'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /gem/lib/uffizzi/cli.rb:65:in `dispatch'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /gem/exe/uffizzi:5:in `<top (required)>'
	from /bundle_cache/ruby/3.0.0/bin/uffizzi:25:in `load'
	from /bundle_cache/ruby/3.0.0/bin/uffizzi:25:in `<top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:478:in `exec'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:23:in `load'
	from /usr/local/bundle/bin/bundle:23:in `<main>'
/usr/local/lib/ruby/3.0.0/net/http.rb:987:in `initialize': Address not available - connect(2) for nil port 80 (Errno::EADDRNOTAVAIL)
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `open'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:985:in `connect'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:959:in `start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:621:in `start'
	from /gem/lib/uffizzi/clients/api/http_client.rb:39:in `make_request'
	from /gem/lib/uffizzi/clients/api/http_client.rb:22:in `make_post_request'
	from /gem/lib/uffizzi/clients/api/api_client.rb:32:in `create_credential'
	from /gem/lib/uffizzi/cli/connect.rb:139:in `ghcr'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /gem/lib/uffizzi/cli.rb:65:in `dispatch'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /gem/exe/uffizzi:5:in `<top (required)>'
	from /bundle_cache/ruby/3.0.0/bin/uffizzi:25:in `load'
	from /bundle_cache/ruby/3.0.0/bin/uffizzi:25:in `<top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:478:in `exec'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:23:in `load'
	from /usr/local/bundle/bin/bundle:23:in `<main>'
bash-5.1#
```
</details>

**Comment by moklidia** [comment]
@NealArw Fixed in this ticket

https://github.com/UffizziCloud/uffizzi_cli/issues/54
