### ISSUE TITLE
uffizzi project delete

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#78]
**Tell us about your request**
Implement support for deleting projects via the CLI.

**Which service(s) is this request for?**
uffizzi_cli

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
A user or automation (e.g. GitHub Action) should be able to delete Uffizzi projects.

**Describe the solution you'd like**
```
$ uffizzi project delete help (also `--help`, `-h`) 

UFFIZZI-PROJECT-DELETE()

NAME
    uffizzi project delete - delete a project

SYNOPSIS
    uffizzi project delete PROJECT_SLUG [UFFIZZI_WIDE_FLAG ...]

DESCRIPTION
    Deletes a project with the given project slug. 

    This command can fail for the following reasons:
      - There is no project with the given project slug
      - The active account does not have permission to delete the project

    For more information on Uffizzi projects, see:
    https://docs.uffizzi.com/cli

UFFIZZI WIDE FLAGS
    These flags are available to all commands: --project. Run $ uffizzi 
    help for details.

EXAMPLES
    To delete a project with project slug my-app-xc8fw, run:

        $ uffizzi project delete my-app-xc8fw
```

**Are you currently working around the issue?**
The user must use a single `default` project

**Additional context**
N/A

**Comment by NealArw** [comment]
1. `bundle exec uffizzi project delete default-3` returns an error:

```
bash-5.1# bundle exec uffizzi project delete default-3
bundler: failed to load command: uffizzi (/bundle_cache/ruby/3.0.0/bin/uffizzi)
/gem/lib/uffizzi/clients/api/api_client.rb:39:in `delete_project': undefined method `make_delete_request' for Uffizzi::HttpClient:Class (NoMethodError)
	from /gem/lib/uffizzi/cli/project.rb:83:in `handle_delete_command'
	from /gem/lib/uffizzi/cli/project.rb:49:in `run'
	from /gem/lib/uffizzi/cli/project.rb:35:in `delete'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /gem/lib/uffizzi/cli.rb:70:in `dispatch'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /gem/exe/uffizzi:5:in `<top (required)>'
	from /bundle_cache/ruby/3.0.0/bin/uffizzi:25:in `load'
	from /bundle_cache/ruby/3.0.0/bin/uffizzi:25:in `<top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:478:in `exec'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:23:in `load'
	from /usr/local/bundle/bin/bundle:23:in `<main>'
bash-5.1#
```

**Comment by moklidia** [comment]
The error was caused by qa conflicts

**Comment by NealArw** [comment]
**TESTED - OK**

```
bash-5.1# bundle exec uffizzi project list
2
1
slug_2
default
test
bash-5.1# bundle exec uffizzi project delete slug_2
Project with slug slug_2 was deleted successfully
bash-5.1# bundle exec uffizzi project delete slug_2
Resource Not Found
bash-5.1# bundle exec uffizzi project list
2
1
default
test
bash-5.1#
```

<img width="638" alt="image" src="https://user-images.githubusercontent.com/89470900/166909777-2d20582f-f570-4543-8018-2dc47ff5b131.png">

**Comment by NealArw** [comment]
@gadkins Hi!

We have a question:
If we set a project as default and then delete this project, do we need to unset the project from the config file?

```
bash-5.1# bundle exec uffizzi project create --name=test-5 --slug=test-5
Project test-5 was successfully created

bash-5.1# bundle exec uffizzi project set-default test-5
Default project has been updated.

bash-5.1# bundle exec uffizzi config list
server = http://web:7000
username = user@example.com
cookie = 
account_id = 1
project = test-5

bash-5.1# bundle exec uffizzi project delete test-5
Project with slug test-5 was deleted successfully

bash-5.1# bundle exec uffizzi config list
server = http://web:7000
username = user@example.com
cookie = 
account_id = 1
project = test-5

```
