### ISSUE TITLE
uffizzi project describe

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#79]
**Tell us about your request**
Implement support for describing project details via `$ uffizzi project describe` subcommand.

**Which service(s) is this request for?**
uffizzi_cli

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
A user or automation (e.g. GitHub Action) should be able to see details about Uffizzi projects, including settings, default compose spec, secret names, preview URLs, metadata (created, name, slug, description, etc).

**Describe the solution you'd like**

The `project describe` subcommand should function similarly to `preview describe`. The default output format should be a JSON object, but the user should be able to specify a pretty print format.

```
$ uffizzi project describe help (also `--help`, `-h`) 

UFFIZZI-PROJECT-DESCRIBE()

NAME
    uffizzi project describe - show metadata for a project

SYNOPSIS
    uffizzi project describe PROJECT_SLUG [UFFIZZI_WIDE_FLAG ...]

DESCRIPTION
    Shows metadata for a project given a valid project slug. 

    This command can fail for the following reasons:
      - There is no project with the given project slug

    For more information on Uffizzi projects, see:
    https://docs.uffizzi.com/cli

FLAGS
    --output FORMAT
       Output format. FORMAT is one of the following: json, pretty. Default is json.

UFFIZZI WIDE FLAGS
    These flags are available to all commands: --project. Run $ uffizzi 
    help for details.

EXAMPLES
    The following command prints metadata for a project with the project
    slug my-app-xc8fw:

        $ uffizzi project describe my-app-xc8fw

    The following command pretty prints metadata for a project with the project
    slug my-app-xc8fw:

        $ uffizzi project describe my-app-xc8fw --output pretty 
```

**Example Output**
```
  $ uffizzi project describe my-app-xc8fw --output pretty 
  Project name: My App
  Project slug: my-app-xc8fw
  Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
    eiusmod tempor incididunt
  Created: Tue, 19 Apr 2022 17:38:18 GMT
  Default compose: https://github.com/example/docker-compose.uffizzi.yml
  Previews:
      - deployment-201 (https://my-app-xc8fw.foo-bar.app.uffizzi.com)
      - deployment-202 (https://pr84-my-app-xc8fw.foo-bar.app.uffizzi.com)
      - deployment-203 (https://pr85-my-app-xc8fw.foo-bar.app.uffizzi.com)
  Secrets:
      - DATABASE_USER
      - DATABASE_PASSWORD
  ...
```

**Are you currently working around the issue?**
No. There is currently no way to see details about a project.

**Additional context**
N/A

**Comment by NealArw** [comment]
`uffizzi project describe default` with mode **--output pretty** returns an error:

```
bash-5.1# bundle exec uffizzi project describe default --output pretty
Project name: default
Project slug: default
Description:
Created: 2022-05-17T10:44:53.090Z
bundler: failed to load command: uffizzi (/bundle_cache/ruby/3.0.0/bin/uffizzi)
/gem/lib/uffizzi/shell.rb:75:in `output_in_pretty_format': undefined method `[]' for nil:NilClass (NoMethodError)
	from /gem/lib/uffizzi/shell.rb:51:in `describe_project'
	from /gem/lib/uffizzi/cli/project.rb:85:in `handle_succeed_describe_response'
	from /gem/lib/uffizzi/cli/project.rb:75:in `handle_describe_command'
	from /gem/lib/uffizzi/cli/project.rb:67:in `run'
	from /gem/lib/uffizzi/cli/project.rb:49:in `describe'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /gem/lib/uffizzi/cli.rb:64:in `dispatch'
	from /bundle_cache/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /gem/exe/uffizzi:5:in `<top (required)>'
	from /bundle_cache/ruby/3.0.0/bin/uffizzi:25:in `load'
	from /bundle_cache/ruby/3.0.0/bin/uffizzi:25:in `<top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:478:in `exec'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:23:in `load'
	from /usr/local/bundle/bin/bundle:23:in `<main>'
```

Project from API:

```
{
    "project": {
        "name": "default",
        "slug": "default",
        "description": null,
        "created_at": "2022-05-17T10:44:53.090Z",
        "deployments": [
            {
                "id": 4,
                "preview_url": "deployment-4.default.app.qa-gke.uffizzi.com",
                "state": "active"
            }
        ],
        "secrets": [
            "TEST_S",
            "TEST_NEAL",
            "POSTGRES_PASSWORD",
            "POSTGRES_USER"
        ],
        "default_compose": null
    }
}
```

**Comment by NealArw** [comment]
There is no information about deployments (previews), but there is one active deployment in the project:

```
bash-5.1# bundle exec uffizzi project describe default --output pretty
Project name: default
Project slug: default
Description:
Created: 2022-05-17T10:44:53.090Z
Default compose:
Previews:
Secrets:
  - TEST_S
  - TEST_NEAL
  - POSTGRES_PASSWORD
  - POSTGRES_USER
  - 
bash-5.1# bundle exec uffizzi project describe default
{"name":"default","slug":"default","description":null,"created_at":"2022-05-17T10:44:53.090Z","deployments":[],"secrets":["TEST_S","TEST_NEAL","POSTGRES_PASSWORD","POSTGRES_USER"],"default_compose":null}

bash-5.1# bundle exec uffizzi preview list
deployment-4
```

**Comment by NealArw** [comment]
**TESTED - OK**

```
bash-5.1# bundle exec uffizzi project describe default --output pretty
Project name: default
Project slug: default
Description: test description
Created: 2022-05-17T10:44:53.090Z
Default compose: /gem/test-compose/uffizzi-compose-webhook-docker.yml
Previews:
  - deployment-8 (https://deployment-8.default.app.qa-gke.uffizzi.com)
Secrets:
  - TEST_S
  - TEST_NEAL
  - POSTGRES_PASSWORD
  - POSTGRES_USER

bash-5.1# bundle exec uffizzi project describe default --output json
{"name":"default","slug":"default","description":"test description","created_at":"2022-05-17T10:44:53.090Z","deployments":[{"id":8,"preview_url":"deployment-8.default.app.qa-gke.uffizzi.com","state":"active"}],"secrets":["TEST_S","TEST_NEAL","POSTGRES_PASSWORD","POSTGRES_USER"],"default_compose":{"source":"/gem/test-compose/uffizzi-compose-webhook-docker.yml"}}

bash-5.1# bundle exec uffizzi project describe default
{"name":"default","slug":"default","description":"test description","created_at":"2022-05-17T10:44:53.090Z","deployments":[{"id":8,"preview_url":"deployment-8.default.app.qa-gke.uffizzi.com","state":"active"}],"secrets":["TEST_S","TEST_NEAL","POSTGRES_PASSWORD","POSTGRES_USER"],"default_compose":{"source":"/gem/test-compose/uffizzi-compose-webhook-docker.yml"}}
bash-5.1#
```

**Comment by AnnaPochepina** [comment]
verified in production
