### ISSUE TITLE
Possible Race Condition for config file handling

### ISSUE THREAD

**Issue by axisofentropy** [UffizziCloud/uffizzi_cli#87]
Describe the bug
I think there may be a race condition in the config file handling. When many `uffizzi preview create` commands are executed simultaneously within a container, sometimes the config file contents get changed to only include the `cookie` but not the server URL or any other values. I don't know why `preview create` is writing to the file at all; maybe 

To Reproduce

```
~ # for i in `seq 42`; do echo $i; uffizzi preview create /app/docker-compose.2022-04-11.yml & done
```

Check contents of `~/.config/uffizzi/config_default.json`

Configuration:
```
$ docker run --interactive --tty --rm --env-file=/home/adam/src/uffizzi_cli/tmp.env -v /home/adam/src/example-voting-app-monorepo:/app --entrypoint=sh uffizzi/cli:latest
```

**Comment by axisofentropy** [comment]
The errors make it look like it's trying (and obviously failing) to connect to IP address `nil`.

```
/usr/local/lib/ruby/3.0.0/net/http.rb:987:in `initialize': Address not available - connect(2) for nil port 80 (Errno::EADDRNOTAVAIL)
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `open'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:985:in `connect'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:959:in `start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:621:in `start'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/clients/api/http_client.rb:33:in `make_request'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/clients/api/http_client.rb:12:in `make_get_request'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/clients/api/api_client.rb:144:in `get_activity_items'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/cli/preview.rb:167:in `block in wait_containers_deploying'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/cli/preview.rb:166:in `loop'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/cli/preview.rb:166:in `wait_containers_deploying'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/cli/preview.rb:153:in `print_deployment_progress'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/cli/preview.rb:117:in `handle_succeed_create_response'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/cli/preview.rb:84:in `handle_create_command'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/cli/preview.rb:59:in `run'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/cli/preview.rb:25:in `create'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/lib/uffizzi/cli.rb:74:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/uffizzi-cli-0.6.0/exe/uffizzi:5:in `<top (required)>'
	from /usr/local/bundle/bin/uffizzi:25:in `load'
	from /usr/local/bundle/bin/uffizzi:25:in `<main>'
```

**Comment by NealArw** [comment]
**TESTED - OK**

Tested with command: `for i in `seq 42`; do echo $i; bundle exec uffizzi preview describe deployment-1 & done`
Config file was not modifed.

**Comment by NealArw** [comment]
**TESTED on prod - OK**

Tested with command:

```
for i in `seq 42`; do echo $i; uffizzi preview describe deployment-1 & done
```
Config file was not modifed.
