### ISSUE TITLE
BUG: [CLI][Prod] Process interruption within preview creation

### ISSUE THREAD

**Issue by NealArw** [UffizziCloud/uffizzi_cli#98]
If a cli process stops within a preview creation it gives the following stacktrace:

```
# uffizzi preview create -o=json compose.yml
[✔] Creating containers...
[⠋] Deploying preview...
  [✔] redis
  [✔] postgres
  [⠸] nginx
  [✔] example-voting-app-worker
  [✔] example-voting-app-vote
  [✔] example-voting-app-result
^C/usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/cli/preview.rb:98:in `rescue in handle_create_command': undefined local variable or method `hostname' for #<Uffizzi::Cli::Preview:0x0000556cd0f91d38 @_invocations={Uffizzi::Cli=>["preview"], Uffizzi::Cli::Preview=>["create"]}, @_initializer=[[], ["-o=json", "compose.yml"], {:shell=>#<Thor::Shell::Color:0x0000556cd0f61638 @base=#<Uffizzi::Cli:0x0000556cd0f5afb8 @_invocations={Uffizzi::Cli=>["preview"], Uffizzi::Cli::Preview=>["create"]}, @_initializer=[["create"], ["-o=json", "compose.yml"], {:shell=>#<Thor::Shell::Color:0x0000556cd0f61638 ...>, :current_command=>#<struct Thor::Command name="preview", description="preview", long_description=nil, usage="preview", options={:project=>#<Thor::Option:0x0000556cd12ee260 @check_default_type=nil, @repeatable=false, @name="project", @description=nil, @required=false, @type=:string, @default=nil, @human_name="project", @banner="PROJECT", @enum=nil, @lazy_default=nil, @aliases=[], @hide=nil, @switch_name="--project">}, ancestor_name=nil>}], @options={}, @args=["create", "-o=json", "compose.yml"], @shell=#<Thor::Shell::Color:0x0000556cd0f61638 ...>>, @mute=false, @padding=0, @always_force=false>, :current_command=>#<struct Thor::Command name="create", description="Create a preview", long_description=nil, usage="create [COMPOSE_FILE]", options={:output=>#<Thor::Option:0x0000556cd1314d98 @check_default_type=nil, @repeatable=false, @name="output", @description=nil, @required=false, @type=:string, @default=nil, @human_name="output", @banner="OUTPUT", @enum=["json", "github-action"], @lazy_default=nil, @aliases=["-o"], @hide=nil, @switch_name="--output">}, ancestor_name="preview">, :invocations=>{Uffizzi::Cli=>["preview"], Uffizzi::Cli::Preview=>["create"]}, :invoked_via_subcommand=>true, :class_options=>{}}], @options={"output"=>"json"}, @args=["compose.yml"], @shell=#<Thor::Shell::Color:0x0000556cd0f61638 @base=#<Uffizzi::Cli:0x0000556cd0f5afb8 @_invocations={Uffizzi::Cli=>["preview"], Uffizzi::Cli::Preview=>["create"]}, @_initializer=[["create"], ["-o=json", "compose.yml"], {:shell=>#<Thor::Shell::Color:0x0000556cd0f61638 ...>, :current_command=>#<struct Thor::Command name="preview", description="preview", long_description=nil, usage="preview", options={:project=>#<Thor::Option:0x0000556cd12ee260 @check_default_type=nil, @repeatable=false, @name="project", @description=nil, @required=false, @type=:string, @default=nil, @human_name="project", @banner="PROJECT", @enum=nil, @lazy_default=nil, @aliases=[], @hide=nil, @switch_name="--project">}, ancestor_name=nil>}], @options={}, @args=["create", "-o=json", "compose.yml"], @shell=#<Thor::Shell::Color:0x0000556cd0f61638 ...>>, @mute=false, @padding=0, @always_force=false>, @parent_options={}, @http_client=#<Uffizzi::HttpClient:0x0000556cd111fb78 @auth_cookie="_uffizzi_app_session=7NMCezbaQ2rStbNht1ywE1pJlQOr0b1V%2F4NBQLDmTl3DQWMV7WdTxNz%2FnT4zHH%2FyHpITbnH3Q%2FN8bRxSjLYzHhIO%2B7cPAIgqN5Dh5kTv0EnRziisdmBfxhUnqO1eruW%2FJPfAKgEu8P1Fz2LBIxWDvsMpvj6GDC0p2scAqKZdV4O1Cgpr4h%2BVXxQiJMNZ%2FaVlW%2BmepgTWRGf5RBt7--n8pKRvV4%2FHDpPpB9--5Jm04RLOzcAHwzLWYVdiMQ%3D%3D", @basic_auth_user=nil, @basic_auth_password=nil>> (NameError)
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/cli/preview.rb:85:in `handle_create_command'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/cli/preview.rb:63:in `run'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/cli/preview.rb:23:in `create'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/cli.rb:64:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/exe/uffizzi:5:in `<top (required)>'
	from /usr/local/bundle/bin/uffizzi:25:in `load'
	from /usr/local/bundle/bin/uffizzi:25:in `<main>'
/usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/services/preview_service.rb:70:in `sleep': Interrupt
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/services/preview_service.rb:70:in `block in display_containers_deploying_status'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/services/preview_service.rb:63:in `loop'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/services/preview_service.rb:63:in `display_containers_deploying_status'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/services/preview_service.rb:52:in `create_deployment'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/services/preview_service.rb:26:in `start_deploy_containers'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/cli/preview.rb:92:in `handle_create_command'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/cli/preview.rb:63:in `run'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/cli/preview.rb:23:in `create'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/lib/uffizzi/cli.rb:64:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/uffizzi-cli-0.7.3/exe/uffizzi:5:in `<top (required)>'
	from /usr/local/bundle/bin/uffizzi:25:in `load'
	from /usr/local/bundle/bin/uffizzi:25:in `<main>'
```

**Comment by NealArw** [comment]
**TESTED - OK**

```
bash-5.1# bundle exec uffizzi preview create -o=json test-compose/uffizzi-vote-app-docker.yml
[✔] Creating containers...
[⠧] Deploying preview...
  [✔] redis
  [✔] postgres
  [⠇] nginx
  [✔] example-voting-app-worker
  [✔] example-voting-app-vote
  [✔] example-voting-app-result
^CThe preview creation was interrupted. The preview deployment-1 has been disabled.
bash-5.1#
```

**Comment by NealArw** [comment]
**TESTED on prod - OK**

```
# uffizzi preview create -o=json compose-vote-app.yml
[✔] Creating containers...
[⠴] Deploying preview...
  [✔] redis
  [✔] postgres
  [⠙] nginx
  [✔] example-voting-app-worker
  [✔] example-voting-app-vote
  [✔] example-voting-app-result
^CThe preview creation was interrupted. The preview deployment-1 has been disabled.
```
